export class OrderErrorConst {
    public columnName = ['id', 'Branch', 'Category', 'Item', 'Country', 'State', 'Amount', 'Actions']
    public contactContext = 'Were here to help! Please provide the following details to our support team for faster assistance:'
    public contactTitle = 'Contact Support'
    public NotSync = 'NotSync'
    public OK = 'OK'
    public orderErrorStaticData = [
        {
          "id": 1,
          "StatusResponse": "Success",
          "ExtPlatform": "PlatformA",
          "State": "New York",
          "Region": "North America",
          "Brcode": 101,
          "Branch": "BranchA",
          "MainCategorySortOrder": 1,
          "MainCategoryId": "MC001",
          "MainCategoryName": "Desserts",
          "CategorySortOrder": 1,
          "CategoryId": "C001",
          "CategoryName": "Cakes",
          "Icode": 12301,
          "Iname": "Chocolate Truffle Cake",
          "Uom": "pcs",
          "RateWithoutTax": "29.99",
          "GST": "5%",
          "OptionSaleYN": "Yes",
          "LiveStatus": "Available",
          "Included_platforms": "Online, Retail",
          "WebItmDescription": "Rich chocolate truffle cake with ganache topping",
          "Recommended": "Yes",
          "OptionGroupName": "Size Options",
          "IndWeight": "1.2 kg",
          "CountryCode": "US",
          "CountryName": "United States",
          "status": "NotSync",
          "syncTime": "2024-12-20T15:00:00Z"
        },
        {
          "id": 2,
          "StatusResponse": "Success",
          "ExtPlatform": "PlatformB",
          "State": "California",
          "Region": "North America",
          "Brcode": 102,
          "Branch": "BranchB",
          "MainCategorySortOrder": 1,
          "MainCategoryId": "MC002",
          "MainCategoryName": "Desserts",
          "CategorySortOrder": 2,
          "CategoryId": "C002",
          "CategoryName": "Pastries",
          "Icode": 12302,
          "Iname": "Strawberry Pastry",
          "Uom": "pcs",
          "RateWithoutTax": "4.99",
          "GST": "5%",
          "OptionSaleYN": "Yes",
          "LiveStatus": "Available",
          "Included_platforms": "Online, Retail",
          "WebItmDescription": "Soft sponge pastry with fresh strawberry cream",
          "Recommended": "Yes",
          "OptionGroupName": "Single Serve",
          "IndWeight": "0.2 kg",
          "CountryCode": "US",
          "CountryName": "United States",
          "status": "NotSync",
          "syncTime": "2024-12-20T15:00:00Z"
        },
        {
          "id": 3,
          "StatusResponse": "Success",
          "ExtPlatform": "PlatformA",
          "State": "Texas",
          "Region": "North America",
          "Brcode": 103,
          "Branch": "BranchC",
          "MainCategorySortOrder": 1,
          "MainCategoryId": "MC003",
          "MainCategoryName": "Desserts",
          "CategorySortOrder": 3,
          "CategoryId": "C003",
          "CategoryName": "Cookies",
          "Icode": 12303,
          "Iname": "Choco Chip Cookies",
          "Uom": "dozen",
          "RateWithoutTax": "9.99",
          "GST": "5%",
          "OptionSaleYN": "Yes",
          "LiveStatus": "Available",
          "Included_platforms": "Online, Retail",
          "WebItmDescription": "Crunchy cookies with rich chocolate chips",
          "Recommended": "No",
          "OptionGroupName": "Pack Size",
          "IndWeight": "0.5 kg",
          "CountryCode": "US",
          "CountryName": "United States",
          "status": "NotSync",
          "syncTime": "2024-12-20T15:00:00Z"
        },
        {
          "id": 4,
          "StatusResponse": "Success",
          "ExtPlatform": "PlatformC",
          "State": "Florida",
          "Region": "North America",
          "Brcode": 104,
          "Branch": "BranchD",
          "MainCategorySortOrder": 2,
          "MainCategoryId": "MC004",
          "MainCategoryName": "Snacks",
          "CategorySortOrder": 1,
          "CategoryId": "C004",
          "CategoryName": "Savories",
          "Icode": 12304,
          "Iname": "Veg Samosa",
          "Uom": "pcs",
          "RateWithoutTax": "2.49",
          "GST": "5%",
          "OptionSaleYN": "Yes",
          "LiveStatus": "Available",
          "Included_platforms": "Retail",
          "WebItmDescription": "Crispy samosas stuffed with spiced potatoes",
          "Recommended": "Yes",
          "OptionGroupName": "Fried Items",
          "IndWeight": "0.15 kg",
          "CountryCode": "US",
          "CountryName": "United States",
          "status": "NotSync",
          "syncTime": "2024-12-20T15:00:00Z"
        },
        {
          "id": 5,
          "StatusResponse": "Success",
          "ExtPlatform": "PlatformD",
          "State": "Illinois",
          "Region": "North America",
          "Brcode": 105,
          "Branch": "BranchE",
          "MainCategorySortOrder": 2,
          "MainCategoryId": "MC004",
          "MainCategoryName": "Snacks",
          "CategorySortOrder": 2,
          "CategoryId": "C005",
          "CategoryName": "Sandwiches",
          "Icode": 12305,
          "Iname": "Cheese Grilled Sandwich",
          "Uom": "pcs",
          "RateWithoutTax": "6.99",
          "GST": "5%",
          "OptionSaleYN": "Yes",
          "LiveStatus": "Available",
          "Included_platforms": "Online, Retail",
          "WebItmDescription": "Grilled sandwich with cheddar cheese filling",
          "Recommended": "Yes",
          "OptionGroupName": "Add-ons",
          "IndWeight": "0.4 kg",
          "CountryCode": "US",
          "CountryName": "United States",
          "status": "NotSync",
          "syncTime": "2024-12-20T15:00:00Z"
        },
        {
          "id": 6,
          "StatusResponse": "Success",
          "ExtPlatform": "PlatformE",
          "State": "Arizona",
          "Region": "North America",
          "Brcode": 106,
          "Branch": "BranchF",
          "MainCategorySortOrder": 1,
          "MainCategoryId": "MC006",
          "MainCategoryName": "Desserts",
          "CategorySortOrder": 4,
          "CategoryId": "C006",
          "CategoryName": "Ice Cream",
          "Icode": 12306,
          "Iname": "Vanilla Sundae",
          "Uom": "cup",
          "RateWithoutTax": "3.99",
          "GST": "5%",
          "OptionSaleYN": "Yes",
          "LiveStatus": "Available",
          "Included_platforms": "Online, Retail",
          "WebItmDescription": "Creamy vanilla ice cream with chocolate sauce",
          "Recommended": "Yes",
          "OptionGroupName": "Toppings",
          "IndWeight": "0.3 kg",
          "CountryCode": "US",
          "CountryName": "United States",
          "status": "NotSync",
          "syncTime": "2024-12-20T15:00:00Z"
        },
        {
          "id": 7,
          "StatusResponse": "Success",
          "ExtPlatform": "PlatformF",
          "State": "Nevada",
          "Region": "North America",
          "Brcode": 107,
          "Branch": "BranchG",
          "MainCategorySortOrder": 2,
          "MainCategoryId": "MC004",
          "MainCategoryName": "Snacks",
          "CategorySortOrder": 3,
          "CategoryId": "C007",
          "CategoryName": "Wraps",
          "Icode": 12307,
          "Iname": "Veg Wrap",
          "Uom": "pcs",
          "RateWithoutTax": "5.49",
          "GST": "5%",
          "OptionSaleYN": "Yes",
          "LiveStatus": "Available",
          "Included_platforms": "Retail",
          "WebItmDescription": "Healthy veg wrap with fresh veggies and sauces",
          "Recommended": "No",
          "OptionGroupName": "Add-ons",
          "IndWeight": "0.35 kg",
          "CountryCode": "US",
          "CountryName": "United States",
          "status": "NotSync",
          "syncTime": "2024-12-20T15:00:00Z"
        },
        {
          "id": 8,
          "StatusResponse": "Success",
          "ExtPlatform": "PlatformG",
          "State": "Ohio",
          "Region": "North America",
          "Brcode": 108,
          "Branch": "BranchH",
          "MainCategorySortOrder": 1,
          "MainCategoryId": "MC007",
          "MainCategoryName": "Beverages",
          "CategorySortOrder": 1,
          "CategoryId": "C008",
          "CategoryName": "Cold Drinks",
          "Icode": 12308,
          "Iname": "Mango Smoothie",
          "Uom": "glass",
          "RateWithoutTax": "4.99",
          "GST": "5%",
          "OptionSaleYN": "Yes",
          "LiveStatus": "Available",
          "Included_platforms": "Retail",
          "WebItmDescription": "Chilled mango smoothie with fresh pulp",
          "Recommended": "Yes",
          "OptionGroupName": "Size Options",
          "IndWeight": "0.4 kg",
          "CountryCode": "US",
          "CountryName": "United States",
          "status": "NotSync",
          "syncTime": "2024-12-20T15:00:00Z"
        },{
          "id": 9,
          "StatusResponse": "Success",
          "ExtPlatform": "PlatformH",
          "State": "Michigan",
          "Region": "North America",
          "Brcode": 109,
          "Branch": "BranchI",
          "MainCategorySortOrder": 2,
          "MainCategoryId": "MC007",
          "MainCategoryName": "Beverages",
          "CategorySortOrder": 2,
          "CategoryId": "C009",
          "CategoryName": "Hot Drinks",
          "Icode": 12309,
          "Iname": "Hot Chocolate",
          "Uom": "cup",
          "RateWithoutTax": "3.99",
          "GST": "5%",
          "OptionSaleYN": "Yes",
          "LiveStatus": "Available",
          "Included_platforms": "Online, Retail",
          "WebItmDescription": "Rich and creamy hot chocolate",
          "Recommended": "Yes",
          "OptionGroupName": "Add-ons",
          "IndWeight": "0.3 kg",
          "CountryCode": "US",
          "CountryName": "United States",
          "status": "NotSync",
          "syncTime": "2024-12-20T15:00:00Z"
        },
        {
          "id": 10,
          "StatusResponse": "Success",
          "ExtPlatform": "PlatformI",
          "State": "Georgia",
          "Region": "North America",
          "Brcode": 110,
          "Branch": "BranchJ",
          "MainCategorySortOrder": 2,
          "MainCategoryId": "MC007",
          "MainCategoryName": "Beverages",
          "CategorySortOrder": 3,
          "CategoryId": "C010",
          "CategoryName": "Shakes",
          "Icode": 12310,
          "Iname": "Oreo Shake",
          "Uom": "glass",
          "RateWithoutTax": "5.99",
          "GST": "5%",
          "OptionSaleYN": "Yes",
          "LiveStatus": "Available",
          "Included_platforms": "Retail",
          "WebItmDescription": "Creamy Oreo milkshake topped with whipped cream",
          "Recommended": "Yes",
          "OptionGroupName": "Toppings",
          "IndWeight": "0.4 kg",
          "CountryCode": "US",
          "CountryName": "United States",
          "status": "NotSync",
          "syncTime": "2024-12-20T15:00:00Z"
        },
        {
          "id": 11,
          "StatusResponse": "Success",
          "ExtPlatform": "PlatformJ",
          "State": "New Jersey",
          "Region": "North America",
          "Brcode": 111,
          "Branch": "BranchK",
          "MainCategorySortOrder": 1,
          "MainCategoryId": "MC008",
          "MainCategoryName": "Snacks",
          "CategorySortOrder": 4,
          "CategoryId": "C011",
          "CategoryName": "Fries",
          "Icode": 12311,
          "Iname": "Loaded Cheese Fries",
          "Uom": "plate",
          "RateWithoutTax": "6.49",
          "GST": "5%",
          "OptionSaleYN": "Yes",
          "LiveStatus": "Available",
          "Included_platforms": "Online, Retail",
          "WebItmDescription": "Crispy fries topped with melted cheddar cheese",
          "Recommended": "Yes",
          "OptionGroupName": "Dipping Sauces",
          "IndWeight": "0.5 kg",
          "CountryCode": "US",
          "CountryName": "United States",
          "status": "NotSync",
          "syncTime": "2024-12-20T15:00:00Z"
        },
        {
          "id": 12,
          "StatusResponse": "Success",
          "ExtPlatform": "PlatformK",
          "State": "Washington",
          "Region": "North America",
          "Brcode": 112,
          "Branch": "BranchL",
          "MainCategorySortOrder": 2,
          "MainCategoryId": "MC009",
          "MainCategoryName": "Desserts",
          "CategorySortOrder": 5,
          "CategoryId": "C012",
          "CategoryName": "Puddings",
          "Icode": 12312,
          "Iname": "Caramel Custard",
          "Uom": "cup",
          "RateWithoutTax": "4.49",
          "GST": "5%",
          "OptionSaleYN": "Yes",
          "LiveStatus": "Available",
          "Included_platforms": "Online, Retail",
          "WebItmDescription": "Silky smooth caramel custard pudding",
          "Recommended": "Yes",
          "OptionGroupName": "Serving Size",
          "IndWeight": "0.25 kg",
          "CountryCode": "US",
          "CountryName": "United States",
          "status": "NotSync",
          "syncTime": "2024-12-20T15:00:00Z"
        },
        {
          "id": 13,
          "StatusResponse": "Success",
          "ExtPlatform": "PlatformL",
          "State": "Colorado",
          "Region": "North America",
          "Brcode": 113,
          "Branch": "BranchM",
          "MainCategorySortOrder": 1,
          "MainCategoryId": "MC010",
          "MainCategoryName": "Snacks",
          "CategorySortOrder": 5,
          "CategoryId": "C013",
          "CategoryName": "Burgers",
          "Icode": 12313,
          "Iname": "Classic Veggie Burger",
          "Uom": "pcs",
          "RateWithoutTax": "7.99",
          "GST": "5%",
          "OptionSaleYN": "Yes",
          "LiveStatus": "Available",
          "Included_platforms": "Online, Retail",
          "WebItmDescription": "Grilled veggie patty with fresh lettuce and tomato",
          "Recommended": "Yes",
          "OptionGroupName": "Add-ons",
          "IndWeight": "0.45 kg",
          "CountryCode": "US",
          "CountryName": "United States",
          "status": "NotSync",
          "syncTime": "2024-12-20T15:00:00Z"
        },
        {
          "id": 14,
          "StatusResponse": "Success",
          "ExtPlatform": "PlatformM",
          "State": "Nevada",
          "Region": "North America",
          "Brcode": 114,
          "Branch": "BranchN",
          "MainCategorySortOrder": 1,
          "MainCategoryId": "MC010",
          "MainCategoryName": "Desserts",
          "CategorySortOrder": 6,
          "CategoryId": "C014",
          "CategoryName": "Brownies",
          "Icode": 12314,
          "Iname": "Fudge Brownie",
          "Uom": "pcs",
          "RateWithoutTax": "2.99",
          "GST": "5%",
          "OptionSaleYN": "Yes",
          "LiveStatus": "Available",
          "Included_platforms": "Retail",
          "WebItmDescription": "Rich and gooey chocolate brownie",
          "Recommended": "Yes",
          "OptionGroupName": "Single Serve",
          "IndWeight": "0.2 kg",
          "CountryCode": "US",
          "CountryName": "United States",
          "status": "NotSync",
          "syncTime": "2024-12-20T15:00:00Z"
        },
        {
          "id": 15,
          "StatusResponse": "Success",
          "ExtPlatform": "PlatformN",
          "State": "Arizona",
          "Region": "North America",
          "Brcode": 115,
          "Branch": "BranchO",
          "MainCategorySortOrder": 1,
          "MainCategoryId": "MC011",
          "MainCategoryName": "Snacks",
          "CategorySortOrder": 6,
          "CategoryId": "C015",
          "CategoryName": "Waffles",
          "Icode": 12315,
          "Iname": "Belgian Waffles",
          "Uom": "pcs",
          "RateWithoutTax": "6.99",
          "GST": "5%",
          "OptionSaleYN": "Yes",
          "LiveStatus": "Available",
          "Included_platforms": "Online, Retail",
          "WebItmDescription": "Crispy and fluffy Belgian waffles",
          "Recommended": "Yes",
          "OptionGroupName": "Toppings",
          "IndWeight": "0.4 kg",
          "CountryCode": "US",
          "CountryName": "United States",
          "status": "NotSync",
          "syncTime": "2024-12-20T15:00:00Z"
        },
        {
          "id": 16,
          "StatusResponse": "Success",
          "ExtPlatform": "PlatformO",
          "State": "Oregon",
          "Region": "North America",
          "Brcode": 116,
          "Branch": "BranchP",
          "MainCategorySortOrder": 1,
          "MainCategoryId": "MC012",
          "MainCategoryName": "Snacks",
          "CategorySortOrder": 7,
          "CategoryId": "C016",
          "CategoryName": "Donuts",
          "Icode": 12316,
          "Iname": "Glazed Donut",
          "Uom": "pcs",
          "RateWithoutTax": "1.99",
          "GST": "5%",
          "OptionSaleYN": "Yes",
          "LiveStatus": "Available",
          "Included_platforms": "Retail",
          "WebItmDescription": "Soft donut with a sugary glaze",
          "Recommended": "Yes",
          "OptionGroupName": "Flavors",
          "IndWeight": "0.25 kg",
          "CountryCode": "US",
          "CountryName": "United States",
          "status": "NotSync",
          "syncTime": "2024-12-20T15:00:00Z"
        },
        {
          "id": 17,
          "StatusResponse": "Success",
          "ExtPlatform": "PlatformP",
          "State": "Utah",
          "Region": "North America",
          "Brcode": 117,
          "Branch": "BranchQ",
          "MainCategorySortOrder": 2,
          "MainCategoryId": "MC012",
          "MainCategoryName": "Desserts",
          "CategorySortOrder": 8,
          "CategoryId": "C017",
          "CategoryName": "Ice Cream",
          "Icode": 12317,
          "Iname": "Vanilla Ice Cream",
          "Uom": "scoop",
          "RateWithoutTax": "3.49",
          "GST": "5%",
          "OptionSaleYN": "Yes",
          "LiveStatus": "Available",
          "Included_platforms": "Online, Retail",
          "WebItmDescription": "Classic vanilla ice cream scoop",
          "Recommended": "Yes",
          "OptionGroupName": "Toppings",
          "IndWeight": "0.3 kg",
          "CountryCode": "US",
          "CountryName": "United States",
          "status": "NotSync",
          "syncTime": "2024-12-20T15:00:00Z"
        }
      ]
      
}